export const MENU_CONFIG = {
  items: [
    {
      id: "dashboard",
      label: "menu.dashboard",
      icon: "🏠",
      path: "/dashboard",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 1,
    },
    {
      id: "payments",
      label: "menu.payments",
      icon: "💳",
      path: "/payments",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 2,
      submenu: [
        {
          id: "payment-history",
          label: "menu.paymentHistory",
          icon: "📋",
          path: "/payments/history",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 1,
        },
        {
          id: "payment-methods",
          label: "menu.paymentMethods",
          icon: "💳",
          path: "/payments/methods",
          roles: ["ADMIN", "DRIVER", "PASSENGER"],
          order: 2,
        },
        {
          id: "payouts",
          label: "menu.payouts",
          icon: "💰",
          path: "/payments/payouts",
          roles: ["ADMIN", "DRIVER", "FLEET_MANAGER"],
          order: 3,
        },
        {
          id: "invoices",
          label: "menu.invoices",
          icon: "🧾",
          path: "/payments/invoices",
          roles: ["ADMIN", "FLEET_MANAGER"],
          order: 4,
        },
      ],
    },
    {
      id: "chat",
      label: "menu.messages",
      icon: "💬",
      path: "/chat",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 3,
      submenu: [
        {
          id: "chat-rooms",
          label: "menu.chat",
          icon: "💬",
          path: "/chat/rooms",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 1,
        },
        {
          id: "support",
          label: "menu.support",
          icon: "🆘",
          path: "/chat/support",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 2,
        },
        {
          id: "notifications",
          label: "menu.notifications",
          icon: "🔔",
          path: "/chat/notifications",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 3,
        },
      ],
    },
    {
      id: "admin",
      label: "menu.admin",
      icon: "⚙️",
      path: "/admin",
      roles: ["ADMIN"],
      order: 4,
      submenu: [
        {
          id: "users",
          label: "menu.users",
          icon: "👥",
          path: "/admin/users",
          roles: ["ADMIN"],
          order: 1,
        },
        {
          id: "roles",
          label: "menu.roles",
          icon: "🔐",
          path: "/admin/roles",
          roles: ["ADMIN"],
          order: 2,
        },
        {
          id: "system-settings",
          label: "menu.systemSettings",
          icon: "⚙️",
          path: "/admin/settings",
          roles: ["ADMIN"],
          order: 3,
        },
      ],
    },
  ],

  permissions: {
    ADMIN: {
      canAccessAll: true,
      canManageUsers: true,
      canManageRoles: true,
      canViewReports: true,
      canManagePayments: true,
    },
    FLEET_MANAGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: true,
      canManagePayments: true,
    },
    DRIVER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
    PASSENGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
  },
};
