export const MENU_CONFIG = {
  items: [
    {
      id: "dashboard",
      label: "menu.dashboard",
      icon: "🏠",
      path: "/test-creation/new",
      roles: ["SUPERADMIN", "ADMIN", "FACULTY"],
    },
    {
      id: "content",
      label: "menu.content",
      icon: "📚",
      path: "/admin/content",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "chapters",
          label: "menu.chapters",
          icon: "📖",
          path: "/admin/content/chapters",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "sections",
          label: "menu.sections",
          icon: "📑",
          path: "/admin/content/sections",
          roles: ["SUPERADMIN", "ADMIN"],
        },

        {
          id: "topics",
          label: "menu.topics",
          icon: "📝",
          path: "/admin/content/topics",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "questions",
          label: "menu.questions",
          icon: "❓",
          path: "/admin/content/questions",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "question-choices",
          label: "menu.questionChoices",
          icon: "⭕",
          path: "/admin/content/question-choices",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "subscriptions",
      label: "menu.subscriptions",
      icon: "💳",
      path: "/admin/subscriptions",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "subscriptions-list",
          label: "menu.subscriptionsList",
          icon: "📋",
          path: "/admin/subscriptions",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "subscription-packages",
          label: "menu.subscriptionPackages",
          icon: "📦",
          path: "/admin/subscriptions/packages",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "package-features",
          label: "menu.packageFeatures",
          icon: "⭐",
          path: "/admin/subscriptions/features",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "my-subscription",
      label: "menu.mySubscription",
      icon: "💳",
      path: "/my-subscription",
      roles: ["STUDENT"],
    },
    {
      id: "products",
      label: "menu.products",
      icon: "📦",
      path: "/admin/products",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "products-list",
          label: "menu.productsList",
          icon: "📋",
          path: "/admin/products",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "product-tags",
          label: "menu.productTags",
          icon: "🏷️",
          path: "/admin/products/tags",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "product-subtypes",
          label: "menu.productSubtypes",
          icon: "🔖",
          path: "/admin/products/subtypes",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "study",
      label: "menu.study",
      icon: "📚",
      path: "/study",
      roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY"],
      submenu: [
        {
          id: "question-bank",
          label: "menu.questionBank",
          icon: "🗂️",
          path: "/study/question-bank",
          roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY"],
        },
        {
          id: "study-materials",
          label: "menu.studyMaterials",
          icon: "📄",
          path: "/study/materials",
          roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY"],
        },
        {
          id: "flashcards",
          label: "menu.flashcards",
          icon: "🃏",
          path: "/study/flashcards",
          roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY"],
        },
        {
          id: "notes",
          label: "menu.notes",
          icon: "📝",
          path: "/study/notes",
          roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY"],
        },
      ],
    },
    {
      id: "test-creation",
      label: "menu.testCreation",
      icon: "✏️",
      path: "/test-creation",
      roles: ["SUPERADMIN", "ADMIN", "FACULTY", "STUDENT", "PASSENGER", "DRIVER", "FLEET_MANAGER"],
      submenu: [
        {
          id: "study-create-test",
          label: "menu.studyCreateTest",
          icon: "📝",
          path: "/test-creation/study-create",
          roles: ["SUPERADMIN", "ADMIN", "FACULTY", "STUDENT", "PASSENGER", "DRIVER", "FLEET_MANAGER"],
        },
        {
          id: "previous-tests",
          label: "menu.previousTests",
          icon: "📊",
          path: "/previous-tests",
          roles: ["SUPERADMIN", "ADMIN", "STUDENT", "FACULTY", "PASSENGER", "DRIVER", "FLEET_MANAGER"],
        },
        {
          id: "test-templates",
          label: "menu.testTemplates",
          icon: "📋",
          path: "/test-creation/templates",
          roles: ["SUPERADMIN", "ADMIN", "FACULTY"],
        },
        {
          id: "question-builder",
          label: "menu.questionBuilder",
          icon: "🔨",
          path: "/test-creation/builder",
          roles: ["SUPERADMIN", "ADMIN", "FACULTY"],
        },
        {
          id: "new-question-builder",
          label: "menu.newQuestionBuilder",
          icon: "🆕",
          path: "/test-creation/new-builder",
          roles: ["SUPERADMIN", "ADMIN", "FACULTY"],
        },
        {
          id: "test-settings",
          label: "menu.testSettings",
          icon: "⚙️",
          path: "/test-creation/settings",
          roles: ["SUPERADMIN", "ADMIN", "FACULTY"],
        },
      ],
    },
    {
      id: "admin",
      label: "menu.admin",
      icon: "⚙️",
      path: "/admin",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "users",
          label: "menu.users",
          icon: "👥",
          path: "/admin/users",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "roles",
          label: "menu.roles",
          icon: "🔐",
          path: "/admin/roles",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "system-settings",
          label: "menu.systemSettings",
          icon: "⚙️",
          path: "/admin/settings",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "tables",
          label: "menu.tables",
          icon: "📊",
          path: "/admin/tables",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "assessments",
      label: "menu.assessments",
      icon: "📝",
      path: "/admin/assessments",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "question-papers",
          label: "menu.questionPapers",
          icon: "📄",
          path: "/admin/assessments/question-papers",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "question-paper-questions",
          label: "menu.questionPaperQuestions",
          icon: "❓",
          path: "/admin/assessments/question-paper-questions",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "misc",
      label: "Misc",
      icon: "⚙️",
      path: "/med-app",
      roles: ["SUPERADMIN", "ADMIN"],
      submenu: [
        {
          id: "zoom-simulation",
          label: "menu.zoomSimulation",
          icon: "📹",
          path: "/zoom",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "robotic",
          label: "menu.robotic",
          icon: "🤖",
          path: "/robotic",
          roles: ["SUPERADMIN", "ADMIN"],
        },
        {
          id: "question-generator",
          label: "menu.questionGenerator",
          icon: "❓",
          path: "/question-generator",
          roles: ["SUPERADMIN", "ADMIN"],
        },
      ],
    },
    {
      id: "chat",
      label: "menu.messages",
      icon: "💬",
      path: "/chat",
      roles: ["SUPERADMIN"],
      submenu: [
        {
          id: "chat-rooms",
          label: "menu.chat",
          icon: "💬",
          path: "/chat/rooms",
          roles: ["SUPERADMIN"],
        },
        {
          id: "support",
          label: "menu.support",
          icon: "🆘",
          path: "/chat/support",
          roles: ["SUPERADMIN"],
        },
        {
          id: "notifications",
          label: "menu.notifications",
          icon: "🔔",
          path: "/chat/notifications",
          roles: ["SUPERADMIN"],
        },
      ],
    },
    {
      id: "payments",
      label: "menu.payments",
      icon: "💳",
      path: "/payments",
      roles: ["SUPERADMIN"],
      submenu: [
        {
          id: "payment-history",
          label: "menu.paymentHistory",
          icon: "📋",
          path: "/payments/history",
          roles: ["SUPERADMIN"],
        },
        {
          id: "payment-methods",
          label: "menu.paymentMethods",
          icon: "💳",
          path: "/payments/methods",
          roles: ["SUPERADMIN"],
        },
        {
          id: "payouts",
          label: "menu.payouts",
          icon: "💰",
          path: "/payments/payouts",
          roles: ["SUPERADMIN"],
        },
        {
          id: "invoices",
          label: "menu.invoices",
          icon: "🧾",
          path: "/payments/invoices",
          roles: ["SUPERADMIN"],
        },
      ],
    },
    {
      id: "development",
      label: "Development",
      icon: "🛠️",
      path: "/development",
      roles: ["SUPERADMIN"],
      submenu: [
        {
          id: "menu-manager",
          label: "Menu Manager",
          icon: "📋",
          path: "/development/menu-manager",
          roles: ["SUPERADMIN"],
        },
        {
          id: "ref-design",
          label: "Ref Design",
          icon: "🎨",
          path: "/development/ref-design",
          roles: ["SUPERADMIN"],
        },
        {
          id: "adv-db-view",
          label: "Advanced DB Viewer",
          icon: "🗄️",
          path: "/development/adv-db-view",
          roles: ["SUPERADMIN"],
        },
        {
          id: "org-chart",
          label: "Org Chart",
          icon: "📊",
          path: "/development/org-chart",
          roles: ["SUPERADMIN"],
        },
      ],
    },
  ],

  /*
     

  */

  permissions: {
    SUPERADMIN: {
      canAccessAll: true,
      canManageUsers: true,
      canManageRoles: true,
      canViewReports: true,
      canManagePayments: true,
    },
    ADMIN: {
      canAccessAll: false,
      canManageUsers: true,
      canManageRoles: false,
      canViewReports: true,
      canManagePayments: false,
    },
    FLEET_MANAGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: true,
      canManagePayments: true,
    },
    DRIVER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
    PASSENGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
  },
};
