export const MENU_CONFIG = {
  items: [
    {
      id: "dashboard",
      label: "menu.dashboard",
      icon: "🏠",
      path: "/test-creation/new",
      roles: ["ADMIN", "FACULTY"],
      order: 1,
    },
    // {
    //   id: "dashboard",
    //   label: "menu.dashboard",
    //   icon: "🏠",
    //   path: "/dashboard",
    //   roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
    //   order: 1,
    // },
    {
      id: "payments",
      label: "menu.payments",
      icon: "💳",
      path: "/payments",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 2,
      submenu: [
        {
          id: "payment-history",
          label: "menu.paymentHistory",
          icon: "📋",
          path: "/payments/history",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 1,
        },
        {
          id: "payment-methods",
          label: "menu.paymentMethods",
          icon: "💳",
          path: "/payments/methods",
          roles: ["ADMIN", "DRIVER", "PASSENGER"],
          order: 2,
        },
        {
          id: "payouts",
          label: "menu.payouts",
          icon: "💰",
          path: "/payments/payouts",
          roles: ["ADMIN", "DRIVER", "FLEET_MANAGER"],
          order: 3,
        },
        {
          id: "invoices",
          label: "menu.invoices",
          icon: "🧾",
          path: "/payments/invoices",
          roles: ["ADMIN", "FLEET_MANAGER"],
          order: 4,
        },
      ],
    },
    {
      id: "chat",
      label: "menu.messages",
      icon: "💬",
      path: "/chat",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 3,
      submenu: [
        {
          id: "chat-rooms",
          label: "menu.chat",
          icon: "💬",
          path: "/chat/rooms",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 1,
        },
        {
          id: "support",
          label: "menu.support",
          icon: "🆘",
          path: "/chat/support",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 2,
        },
        {
          id: "notifications",
          label: "menu.notifications",
          icon: "🔔",
          path: "/chat/notifications",
          roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
          order: 3,
        },
      ],
    },
    {
      id: "study",
      label: "menu.study",
      icon: "📚",
      path: "/study",
      roles: ["ADMIN", "STUDENT", "FACULTY"],
      order: 3,
      submenu: [
        {
          id: "question-bank",
          label: "menu.questionBank",
          icon: "🗂️",
          path: "/study/question-bank",
          roles: ["ADMIN", "STUDENT", "FACULTY"],
          order: 1,
        },
        {
          id: "study-materials",
          label: "menu.studyMaterials",
          icon: "📄",
          path: "/study/materials",
          roles: ["ADMIN", "STUDENT", "FACULTY"],
          order: 2,
        },
        {
          id: "flashcards",
          label: "menu.flashcards",
          icon: "🃏",
          path: "/study/flashcards",
          roles: ["ADMIN", "STUDENT", "FACULTY"],
          order: 3,
        },
        {
          id: "notes",
          label: "menu.notes",
          icon: "📝",
          path: "/study/notes",
          roles: ["ADMIN", "STUDENT", "FACULTY"],
          order: 4,
        },
      ],
    },
    {
      id: "test-creation",
      label: "menu.testCreation",
      icon: "✏️",
      path: "/test-creation",
      roles: ["ADMIN", "FACULTY"],
      order: 4,
      submenu: [
        {
          id: "study-create-test",
          label: "menu.studyCreateTest",
          icon: "📝",
          path: "/test-creation/study-create",
          roles: ["ADMIN", "FACULTY"],
          order: 1,
        },
        {
          id: "previous-tests",
          label: "menu.previousTests",
          icon: "📊",
          path: "/previous-tests",
          roles: ["ADMIN", "STUDENT", "FACULTY"],
          order: 2,
        },
        {
          id: "test-templates",
          label: "menu.testTemplates",
          icon: "📋",
          path: "/test-creation/templates",
          roles: ["ADMIN", "FACULTY"],
          order: 3,
        },
        {
          id: "question-builder",
          label: "menu.questionBuilder",
          icon: "🔨",
          path: "/test-creation/builder",
          roles: ["ADMIN", "FACULTY"],
          order: 4,
        },
        {
          id: "test-settings",
          label: "menu.testSettings",
          icon: "⚙️",
          path: "/test-creation/settings",
          roles: ["ADMIN", "FACULTY"],
          order: 5,
        },
      ],
    },
    {
      id: "zoom-simulation",
      label: "menu.zoomSimulation",
      icon: "📹",
      path: "/zoom",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 6,
    },
    {
      id: "testing",
      label: "menu.testing",
      icon: "🧪",
      path: "/testing",
      roles: ["ADMIN", "DRIVER", "PASSENGER", "FLEET_MANAGER"],
      order: 7,
    },
    {
      id: "admin",
      label: "menu.admin",
      icon: "⚙️",
      path: "/admin",
      roles: ["ADMIN"],
      order: 8,
      submenu: [
        {
          id: "users",
          label: "menu.users",
          icon: "👥",
          path: "/admin/users",
          roles: ["ADMIN"],
          order: 1,
        },
        {
          id: "roles",
          label: "menu.roles",
          icon: "🔐",
          path: "/admin/roles",
          roles: ["ADMIN"],
          order: 2,
        },
        {
          id: "system-settings",
          label: "menu.systemSettings",
          icon: "⚙️",
          path: "/admin/settings",
          roles: ["ADMIN"],
          order: 3,
        },
        {
          id: "tables",
          label: "menu.tables",
          icon: "📊",
          path: "/admin/tables",
          roles: ["ADMIN"],
          order: 4,
        },
      ],
    },
  ],

  permissions: {
    ADMIN: {
      canAccessAll: true,
      canManageUsers: true,
      canManageRoles: true,
      canViewReports: true,
      canManagePayments: true,
    },
    FLEET_MANAGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: true,
      canManagePayments: true,
    },
    DRIVER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
    PASSENGER: {
      canAccessAll: false,
      canManageUsers: false,
      canManageRoles: false,
      canViewReports: false,
      canManagePayments: false,
    },
  },
};
