import {
  Car,
  CreditCard,
  MessageSquare,
  MapPin,
  Truck,
  Settings,
  FileText,
  Activity,
  Bell,
  AlertTriangle,
  Clock,
  Users,
  Shield,
  BookOpen,
  HelpCircle,
  Pencil,
  LayoutGrid,
  Package,
  BookMarked,
  Tag,
  FolderTree,
  Layers,
  CircleDot,
  Wrench,
  Palette,
  Database,
  Zap,
  Building2,
  Star,
  Sparkles,
  Target,
  Trophy,
  CalendarDays,
  Inbox,
  Flag,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

// Icon mapping for menu items (emoji keys from menu.config)
export const iconMap: Record<string, LucideIcon> = {
  "🏠": LayoutGrid,
  "🚗": Car,
  "💳": CreditCard,
  "💬": MessageSquare,
  "📍": MapPin,
  "🚛": Truck,
  "⚙️": Settings,
  "📋": FileText,
  "📊": Activity,
  "📱": Bell,
  "💰": CreditCard,
  "🧾": FileText,
  "🆘": AlertTriangle,
  "🔔": Bell,
  "🚏": MapPin,
  "🏁": MapPin,
  "⭐": Star,
  "👨‍💼": Users,
  "🗺️": MapPin,
  "🔧": Settings,
  "⛽": Activity,
  "👥": Users,
  "🔐": Shield,
  "📝": FileText,
  "📚": BookOpen,
  "❓": HelpCircle,
  "✏️": Pencil,
  "📄": FileText,
  "🃏": Layers,
  "🗂️": FolderTree,
  "🛠️": Wrench,
  "📦": Package,
  "🏗️": Building2,
  "🏷️": Tag,
  "📖": BookMarked,
  "⭕": CircleDot,
  "🎨": Palette,
  "🗄️": Database,
  "⚡": Zap,
  "🛡️": Shield,
  "✨": Sparkles,
  "🎯": Target,
  "🏆": Trophy,
  "📅": CalendarDays,
  "📨": Inbox,
  "🚩": Flag,
};
