import {
  Home,
  Car,
  CreditCard,
  MessageSquare,
  MapPin,
  Truck,
  Settings,
  FileText,
  Activity,
  Bell,
  AlertTriangle,
  Clock,
  Users,
  Shield,
} from "lucide-react";

// Icon mapping for menu items
export const iconMap: { [key: string]: any } = {
  "🏠": Home,
  "🚗": Car,
  "💳": CreditCard,
  "💬": MessageSquare,
  "📍": MapPin,
  "🚛": Truck,
  "⚙️": Settings,
  "📋": FileText,
  "📊": Activity,
  "📱": Bell,
  "💰": CreditCard,
  "🧾": FileText,
  "🆘": AlertTriangle,
  "🔔": Bell,
  "🚏": MapPin,
  "🏁": MapPin,
  "⭐": Clock,
  "👨‍💼": Users,
  "🗺️": MapPin,
  "🔧": Settings,
  "⛽": Activity,
  "👥": Users,
  "🔐": Shield,
  "📝": FileText,
};

