-- Expand AchievementMetric enum with AI tutor, planner, study groups, MedPrep.

ALTER TABLE `achievements` MODIFY COLUMN `metric` ENUM(
  'QUESTIONS_ANSWERED',
  'CORRECT_ANSWERS',
  'TESTS_COMPLETED',
  'FLASHCARDS_REVIEWED',
  'NOTES_CREATED',
  'STREAK_DAYS',
  'STUDY_MINUTES',
  'DISCUSSION_POSTS',
  'GOAL_COMPLETED',
  'AI_TUTOR_MESSAGES',
  'STUDY_TASKS_COMPLETED',
  'STUDY_GROUP_POSTS',
  'MEDPREP_CONVERSATIONS'
) NOT NULL;
