-- Additional achievement metrics: reports, feedback, mock exams, group joins.

ALTER TABLE `achievements` MODIFY COLUMN `metric` ENUM(
  'QUESTIONS_ANSWERED',
  'CORRECT_ANSWERS',
  'TESTS_COMPLETED',
  'FLASHCARDS_REVIEWED',
  'NOTES_CREATED',
  'STREAK_DAYS',
  'STUDY_MINUTES',
  'DISCUSSION_POSTS',
  'GOAL_COMPLETED',
  'AI_TUTOR_MESSAGES',
  'STUDY_TASKS_COMPLETED',
  'STUDY_GROUP_POSTS',
  'MEDPREP_CONVERSATIONS',
  'QUESTION_REPORTS_SUBMITTED',
  'FEEDBACK_TICKETS_SUBMITTED',
  'MOCK_EXAMS_COMPLETED',
  'STUDY_GROUPS_JOINED'
) NOT NULL;
